### ISSUE TITLE
Constructor impoperly checking for valid ticker

### ISSUE THREAD

**Issue by Svehlajj** [se2832/ay18-lab-07-the-team-lab7#1]
Defect in Line 91 - the code is setting the symbol if it finds that it's _not_ a valid ticker. For example, if the ticker "F" is passed in, it will not set the ticker and throw an exception even though F is a valid stock ticker.

**Comment by lxlyif** [comment]
Fixed the code with commit 95bfc4e4896f07dbb99e5dc3660234ef3554bfbb The conditional had a negation where it should not have one.
